spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
    instance:
      prefix-ip-address: true
    client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"