apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
  selector:
    matchLabels:
      app:  orderapp-service
  replicas: 3
  template:
    metadata:
      labels:
        app:  orderapp-service
    spec:
      containers:
      - name:  orderapp-service
        image: nisargakunder/orderapp-1.2
        ports:
        - name: "app-port"
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: orderapp-svc
spec:
  type: NodePort 
  selector:
    app: orderapp-service
  ports:
  - port: 8080
    targetPort: 8081
    nodePort: 30007
