apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nisargakunder/orderapp-1.2
    imagePullPolicy: Always
    ports:
      - containerPort: 8080