version: "3.8"

services:
  currency-exchange:
    build: ./currency-exchange
    ports:
      - "8000:8000"
    networks:
      - currency-network

  currency-conversion:
    build: ./currency-conversion
    ports:
      - "8100:8100"
    depends_on:
      - currency-exchange
    networks:
      - currency-network

networks:
  currency-network:
