spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        failure-rate-threshold: 5
        wait-duration-in-open-state: 10s
        auto-transition-from-open-to-half-open-enabled: true
        wait-duration-in-half-open-state: 5s